project:
  type: website
  output-dir: docs

website:
  title: "ARRO"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
  page-footer:
    left: |
      © 2025 Ruth Ogal.
    right: |
      Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left
    code-link: true
    link-external-newwindow: true
