<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="dcterms.date" content="2024-09-07">
<title>Using logistic regression to predict income levels – ARRO</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f3c2ea88cadbcfb37ba28ffa2c97cfc1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ARRO</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
<li><a href="#dataset-information" id="toc-dataset-information" class="nav-link active" data-scroll-target="#dataset-information">Dataset Information</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#build-model" id="toc-build-model" class="nav-link" data-scroll-target="#build-model">Build Model</a></li>
  <li><a href="#model-evaluation" id="toc-model-evaluation" class="nav-link" data-scroll-target="#model-evaluation">Model Evaluation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></nav>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Using logistic regression to predict income levels</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">R</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="dataset-information" class="level2"><h2 class="anchored" data-anchor-id="dataset-information">Dataset Information</h2>
<p>The Adult dataset <span class="citation" data-cites="adult_2">(<a href="#ref-adult_2" role="doc-biblioref">Becker and Kohavi 1996</a>)</span>, accessible from the <a href="https://archive.ics.uci.edu/dataset/2/adult">UCI Machine Learning Repository</a>, is a sample from the 1994 US census database comprising 15 variables. A description of each variable is given below.</p>
<table class="caption-top table" data-quarto-postprocess="true">
<thead><tr class="header">
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>age</td>
<td>Age</td>
</tr>
<tr class="even">
<td>workclass</td>
<td>Employment status</td>
</tr>
<tr class="odd">
<td>fnlwgt</td>
<td>Final weight, i.e., the number of people in a given row</td>
</tr>
<tr class="even">
<td>education</td>
<td>Highest level of education</td>
</tr>
<tr class="odd">
<td>education-num</td>
<td>Highest level of education in numerical form</td>
</tr>
<tr class="even">
<td>marital_status</td>
<td>Marital status</td>
</tr>
<tr class="odd">
<td>occupation</td>
<td>Occupation</td>
</tr>
<tr class="even">
<td>relationship</td>
<td>Family relationship</td>
</tr>
<tr class="odd">
<td>race</td>
<td>Race</td>
</tr>
<tr class="even">
<td>sex</td>
<td>Sex/gender</td>
</tr>
<tr class="odd">
<td>capital_gain</td>
<td>Capital gain for an individual</td>
</tr>
<tr class="even">
<td>capital_loss</td>
<td>Capital loss for an individual</td>
</tr>
<tr class="odd">
<td>hours_per_week</td>
<td>Working hours per week</td>
</tr>
<tr class="even">
<td>native_country</td>
<td>Country of birth</td>
</tr>
<tr class="odd">
<td>income</td>
<td>Whether an individual makes more than $50,000 annually</td>
</tr>
</tbody>
</table>
<p><strong>Objective:</strong> Use logistic regression to build a model that predicts a person’s income group, categorized as &lt;=50K or &gt;50K.</p>
<p>As we have already downloaded the data, we load it in R using the code below. The dataset consists of two parts: the training set, <code>adult.data</code>, and the test set, <code>adult.test</code>. We start by loading the training set, which is vital for exploration exercises.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Read train data</span></span>
<span><span class="va">train_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"C:/Users/User/Desktop/Logistic_Regression_ADULT/Data/adult.data"</span>, header <span class="op">=</span> <span class="cn">FALSE</span>, sep <span class="op">=</span> <span class="st">","</span>, strip.white <span class="op">=</span> <span class="cn">TRUE</span>, stringsAsFactors <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co"># Name columns</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"workclass"</span>, <span class="st">"fnlwgt"</span>, <span class="st">"education"</span>, <span class="st">"education_num"</span>, <span class="st">"marital_status"</span>, <span class="st">"occupation"</span>, <span class="st">"relationship"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>, <span class="st">"capital_gain"</span>, <span class="st">"capital_loss"</span>, <span class="st">"hours_per_week"</span>, <span class="st">"native_country"</span>, <span class="st">"income"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="exploratory-data-analysis" class="level2"><h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Logistic regression makes the following assumptions about the data:</p>
<ul>
<li><p>The target variable is binary.</p></li>
<li><p>Absence of multicollinearity among the predictor variables.</p></li>
<li><p>There are no outliers in the data.</p></li>
<li><p>A linear relationship exists between continuous predictors and the logit of the outcome.</p></li>
</ul>
<p>We perform exploratory data analysis (EDA) before building the model to check whether the data meets these assumptions. EDA also helps with feature selection and reveals possible relationships between variables.</p>
<p><strong>Task 1: Load required packages.</strong></p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://wilkelab.org/cowplot/">cowplot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/topepo/caret/">caret</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Task 2: Determine the internal structure of the dataset.</strong></p>
<p>We use the <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> function to gain an overview of the dataset. This function provides information on dataset properties like dimension and data types.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   32561 obs. of  15 variables:
 $ age           : int  39 50 38 53 28 37 49 52 31 42 ...
 $ workclass     : Factor w/ 9 levels "?","Federal-gov",..: 8 7 5 5 5 5 5 7 5 5 ...
 $ fnlwgt        : int  77516 83311 215646 234721 338409 284582 160187 209642 45781 159449 ...
 $ education     : Factor w/ 16 levels "10th","11th",..: 10 10 12 2 10 13 7 12 13 10 ...
 $ education_num : int  13 13 9 7 13 14 5 9 14 13 ...
 $ marital_status: Factor w/ 7 levels "Divorced","Married-AF-spouse",..: 5 3 1 3 3 3 4 3 5 3 ...
 $ occupation    : Factor w/ 15 levels "?","Adm-clerical",..: 2 5 7 7 11 5 9 5 11 5 ...
 $ relationship  : Factor w/ 6 levels "Husband","Not-in-family",..: 2 1 2 1 6 6 2 1 2 1 ...
 $ race          : Factor w/ 5 levels "Amer-Indian-Eskimo",..: 5 5 5 3 3 5 3 5 5 5 ...
 $ sex           : Factor w/ 2 levels "Female","Male": 2 2 2 2 1 1 1 2 1 2 ...
 $ capital_gain  : int  2174 0 0 0 0 0 0 0 14084 5178 ...
 $ capital_loss  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ hours_per_week: int  40 13 40 40 40 40 16 45 50 40 ...
 $ native_country: Factor w/ 42 levels "?","Cambodia",..: 40 40 40 40 6 40 24 40 40 40 ...
 $ income        : Factor w/ 2 levels "&lt;=50K","&gt;50K": 1 1 1 1 1 1 1 2 2 2 ...</code></pre>
</div>
</div>
<p>The output from <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> shows that the training dataset has 32,561 observations and 15 variables. Our target variable is income, which has two categories &lt;=50K and &gt;50K. Therefore, we can use logistic regression to build a binary classification model.</p>
<p>We also notice that the factor variables <code>workclass</code>, <code>occupation</code>, and <code>native_country</code> include levels denoted by a “?”. Upon examining the Variables Table provided at the UCI Machine Learning Repository within the Dataset Information section, we find that these columns have missing values. We conclude that the “?” symbol represents missing data.</p>
<p><strong>Task 3: Handle missing data</strong></p>
<p>The presence of missing data in a regression model can significantly impair the model’s accuracy in predicting responses. In this task, we examine the proportion of missing values in the <code>workclass</code>, <code>occupation</code>, and <code>native_country</code> columns of the training data.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Percentage of missing values in workclass</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">==</span> <span class="st">'?'</span>, <span class="op">]</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.638647</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Percentage of missing values in occupation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">==</span> <span class="st">'?'</span>, <span class="op">]</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.660146</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Percentage of missing values in native_country</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span><span class="va">train_data</span><span class="op">$</span><span class="va">native_country</span> <span class="op">==</span> <span class="st">'?'</span>, <span class="op">]</span><span class="op">)</span> <span class="op">*</span> <span class="fl">100</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.790486</code></pre>
</div>
</div>
<p>We find that the highest percentage of missing values occurs in the <code>workclass</code> and <code>occupation</code> variables, with about 5% of the training data missing in each case. As we’d like to retain these missing values, we recode them as “Missing”, creating an additional category for each variable.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span>, <span class="st">"?"</span> <span class="op">=</span> <span class="st">"Missing"</span><span class="op">)</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span>, <span class="st">"?"</span> <span class="op">=</span> <span class="st">"Missing"</span><span class="op">)</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">native_country</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">native_country</span>, <span class="st">"?"</span> <span class="op">=</span> <span class="st">"Missing"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Task 4: Discard zero-variance and near-zero variance independent variables.</strong></p>
<p>A zero-variance variable has only one unique value, while a near-zero-variance variable has very few unique values. These variables are also termed low cardinality variables, where cardinality refers to the number of unique values a variable has. Because they contain little information, they are unimportant to the analysis <span class="citation" data-cites="boehmke2019">(<a href="#ref-boehmke2019" role="doc-biblioref">Boehmke and Greenwell 2019</a>)</span>. We use the <code><a href="https://rdrr.io/pkg/caret/man/nearZeroVar.html">nearZeroVar()</a></code> function from the <code>caret</code> package to identify these variables in the training data.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">X</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/caret/man/nearZeroVar.html">nearZeroVar</a></span><span class="op">(</span><span class="va">train_data</span>, saveMetrics <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">X</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                freqRatio percentUnique zeroVar   nzv
age              1.011261   0.224194589   FALSE FALSE
workclass        8.931917   0.027640429   FALSE FALSE
fnlwgt           1.000000  66.484444581   FALSE FALSE
education        1.440269   0.049138540   FALSE FALSE
education_num    1.440269   0.049138540   FALSE FALSE
marital_status   1.401853   0.021498111   FALSE FALSE
occupation       1.010002   0.046067381   FALSE FALSE
relationship     1.588561   0.018426952   FALSE FALSE
race             8.903969   0.015355794   FALSE FALSE
sex              2.023025   0.006142317   FALSE FALSE
capital_gain    86.020173   0.365467891   FALSE  TRUE
capital_loss   153.673267   0.282546605   FALSE  TRUE
hours_per_week   5.398013   0.288688922   FALSE FALSE
native_country  45.365474   0.128988667   FALSE  TRUE
income           3.152659   0.006142317   FALSE FALSE</code></pre>
</div>
</div>
<p>From the above output, the training data has no zero-variance variables but contains several near-zero-variance variables, namely, <code>capital_gain</code>, <code>capital_loss</code>, and <code>native_country</code>. We use histograms to explore <code>capital_gain</code> and <code>capital_loss</code> further.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Remove scientific notation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">999</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Histogram of Capital Gain</span></span>
<span><span class="va">cg_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">capital_gain</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">20</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Capital Gain"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span>, plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_minimal_grid.html">theme_minimal_grid</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Histogram of Capital Loss</span></span>
<span><span class="va">cl_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">capital_loss</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">20</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Capital Loss"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span>, plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_minimal_grid.html">theme_minimal_grid</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Use plot_grid() from cowplot to arrange plots on grid</span></span>
<span><span class="fu"><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid</a></span><span class="op">(</span><span class="va">cg_plot</span>, <span class="va">cl_plot</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'A'</span>, <span class="st">'B'</span><span class="op">)</span>, label_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of A) capital_gain and B) capital_loss among the sample population.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-1" class="quarto-xref">Figure&nbsp;1</a> reveals that the distributions of <code>capital_gain</code> and <code>capital_loss</code> are strongly skewed to the right, with most observations being zero. Therefore, we discard these two variables.</p>
<p>In addition, the frequency distribution of <code>native_country</code> shown below indicates that almost 90% (29170/32561) of all entries fall within the <code>United-States</code> category. Because of this heavy skewness, we exclude this variable from our analysis.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Frequencies of levels in native_country</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">native_country</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Missing                   Cambodia 
                       583                         19 
                    Canada                      China 
                       121                         75 
                  Columbia                       Cuba 
                        59                         95 
        Dominican-Republic                    Ecuador 
                        70                         28 
               El-Salvador                    England 
                       106                         90 
                    France                    Germany 
                        29                        137 
                    Greece                  Guatemala 
                        29                         64 
                     Haiti         Holand-Netherlands 
                        44                          1 
                  Honduras                       Hong 
                        13                         20 
                   Hungary                      India 
                        13                        100 
                      Iran                    Ireland 
                        43                         24 
                     Italy                    Jamaica 
                        73                         81 
                     Japan                       Laos 
                        62                         18 
                    Mexico                  Nicaragua 
                       643                         34 
Outlying-US(Guam-USVI-etc)                       Peru 
                        14                         31 
               Philippines                     Poland 
                       198                         60 
                  Portugal                Puerto-Rico 
                        37                        114 
                  Scotland                      South 
                        12                         80 
                    Taiwan                   Thailand 
                        51                         18 
           Trinadad&amp;Tobago              United-States 
                        19                      29170 
                   Vietnam                 Yugoslavia 
                        67                         16 </code></pre>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop non-informative columns</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">capital_gain</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">capital_loss</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">native_country</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Task 5: Discard closely related independent variables.</strong></p>
<p>Two variables are considered collinear when they are so strongly correlated that it is difficult to determine their individual effects on the target variable. When this type of relationship occurs between more than two variables, we refer to it as multicollinearity. In the training dataset, <code>education</code> and <code>education_num</code> are collinear, as <code>education_num</code> is simply a numeric representation of <code>education</code>. The two variables contain the same information, so we discard one, i.e., <code>education_num</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop one of a pair of collinear variables</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">education_num</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Task 6: Discard variables that aren’t important to the analysis.</strong></p>
<p>Here, we discard <code>fnlwgt</code> and <code>relationship</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop irrelevant variables</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">fnlwgt</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">relationship</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Task 7: Lump levels of independent categorical features with few observations.</strong></p>
<p>The independent categorical variables in the dataset are <code>workclass</code>, <code>education</code>, <code>marital_status</code>, <code>occupation</code>, <code>race</code>, and <code>sex</code>. We explore each of these variables to determine instances where level lumping can be applied to reduce the noise in the data.</p>
<p><strong>Lump <code>workclass</code> levels</strong></p>
<p>We use a barplot to compare the number of people belonging to each <code>workclass</code> level.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Barplot of workclass</span></span>
<span><span class="va">wc_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">workclass</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Work Class"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">wc_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of individuals across workclass levels.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-2" class="quarto-xref">Figure&nbsp;2</a> shows that the two levels, <code>Without-pay</code> and <code>Never-worked</code> have very few observations. So, we lump them together with the Missing in a level called “Other/Missing”. We also lump <code>State-gov</code>, <code>Local-gov</code>, and <code>Federal-gov</code> into a new level called “Gov,” as they all pertain to government-related work. <code>Self-emp-not-inc</code> and <code>Self-emp-inc</code> are consolidated into a new level called “Self-emp,” as both are related to self-employment.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Change names of workclass levels</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span>, <span class="st">"Missing"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"Federal-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Local-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Never-worked"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"Self-emp-inc"</span> <span class="op">=</span> <span class="st">"Self-emp"</span>, <span class="st">"Self-emp-not-inc"</span> <span class="op">=</span> <span class="st">"Self-emp"</span>, <span class="st">"State-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Without-pay"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check workclass level frequencies</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Other/Missing           Gov       Private      Self-emp 
         1857          4351         22696          3657 </code></pre>
</div>
</div>
<p>We want the first (base) level of <code>workclass</code> to be a meaningful quantity that can later help with interpreting regression results. So, we use the <code><a href="https://rdrr.io/r/stats/relevel.html">relevel()</a></code> function to reorder these levels, removing “Other/Missing” as the base level.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">workclass</span>, ref <span class="op">=</span> <span class="st">"Gov"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>education</code> levels</strong></p>
<p>The barplot in <a href="#fig-3" class="quarto-xref">Figure&nbsp;3</a> explores the distribution of people by <code>education</code>. Here is the code used to create this plot:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Barplot of education</span></span>
<span><span class="va">ed_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">education</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Education"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ed_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of individuals across education levels.
</figcaption></figure>
</div>
</div>
</div>
<p>We see that all levels from <code>Preschool</code> to <code>12th grade</code> have somewhat low frequencies. So, we lump these levels into a new category called <code>Preschool-12th</code>. We also merge <code>Assoc-voc</code> and <code>Assoc-acdm</code> into a single level called <code>Associate</code>, as shown in the code below.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode education levels</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">education</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">education</span>, <span class="st">"10th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"11th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"12th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"1st-4th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"5th-6th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"7th-8th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"9th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"Assoc-acdm"</span> <span class="op">=</span> <span class="st">"Associate"</span>, <span class="st">"Assoc-voc"</span> <span class="op">=</span> <span class="st">"Associate"</span>, <span class="st">"Preschool"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">education</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Preschool-12th      Associate      Bachelors      Doctorate        HS-grad 
          4253           2449           5355            413          10501 
       Masters    Prof-school   Some-college 
          1723            576           7291 </code></pre>
</div>
</div>
<p><strong>Lump <code>marital_status</code> levels</strong></p>
<p>The barplot in <a href="#fig-4" class="quarto-xref">Figure&nbsp;4</a> explores the distribution of people by <code>marital_status</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Barplot of marital_status</span></span>
<span><span class="va">ms_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">marital_status</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Marital Status"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ms_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-4-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Distribution of individuals across marital_status levels.
</figcaption></figure>
</div>
</div>
</div>
<p>We lump <code>Married-spouse-absent</code>, <code>Married-civ-spouse</code>, and <code>Married-AF-spouse</code> into a level called “Married”, as they all denote married people. By doing so, we reduce the number of levels in this variable to 5.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode marital_status levels</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">marital_status</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">marital_status</span>, <span class="st">"Married-AF-spouse"</span> <span class="op">=</span> <span class="st">"Married"</span>, <span class="st">"Married-civ-spouse"</span> <span class="op">=</span> <span class="st">"Married"</span>, <span class="st">"Married-spouse-absent"</span> <span class="op">=</span> <span class="st">"Married"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">marital_status</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Divorced       Married Never-married     Separated       Widowed 
         4443         15417         10683          1025           993 </code></pre>
</div>
</div>
<p><strong>Lump <code>occupation</code> levels</strong></p>
<p>The barplot in <a href="#fig-5" class="quarto-xref">Figure&nbsp;5</a> illustrates the counts of people in each level of occupation. Here is the code used to create this plot.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">oc_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">occupation</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Occupation"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">oc_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-5-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Distribution of individuals across occupation levels.
</figcaption></figure>
</div>
</div>
</div>
<p>We create the following new levels for occupation:</p>
<ol type="1">
<li>Service-sales-workers: Protective-serv, Priv-house-serv, Other-service, Sales</li>
<li>Managers: Exec-managerial</li>
<li>Professionals: Prof-specialty</li>
<li>Technical: Tech-support</li>
<li>Clerical: Adm-clerical</li>
<li>Labor-trades: Machine-op-inspct, Handlers-cleaners, Farming-fishing, Craft-repair, Transport-moving</li>
<li>Others: Armed-Forces, Missing</li>
</ol>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode occupation levels</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span>, <span class="st">"Protective-serv"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Sales"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Priv-house-serv"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Other-service"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Exec-managerial"</span> <span class="op">=</span> <span class="st">"Managers"</span>, <span class="st">"Prof-specialty"</span> <span class="op">=</span> <span class="st">"Professionals"</span>, <span class="st">"Tech-support"</span> <span class="op">=</span> <span class="st">"Technical"</span>, <span class="st">"Adm-clerical"</span> <span class="op">=</span> <span class="st">"Clerical"</span>, <span class="st">"Machine-op-inspct"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Handlers-cleaners"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Farming-fishing"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Craft-repair"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Transport-moving"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Armed-Forces"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"Missing"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        Other/Missing              Clerical          Labor-trades 
                 1852                  3770                 10062 
             Managers Service-sales-workers         Professionals 
                 4066                  7743                  4140 
            Technical 
                  928 </code></pre>
</div>
</div>
<p>We also reorder the levels of occupation so that the first level is <code>Clerical</code>, a more meaningful quantity than <code>Other/Missing</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">occupation</span>, ref <span class="op">=</span> <span class="st">"Clerical"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>race</code> levels</strong></p>
<p>The barplot in <a href="#fig-6" class="quarto-xref">Figure&nbsp;6</a> shows the counts of people by <code>race</code>. Here is the code used to create it:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">r_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">race</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Race"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">r_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-6-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Distribution of individuals by race.
</figcaption></figure>
</div>
</div>
</div>
<p>We see that more than 20000 people are white, and the next most populous race is black, with less than 5000 people. To simplify our analysis, we regroup race into two levels, <code>White</code> and <code>Non-white</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode race levels</span></span>
<span><span class="va">train_data</span><span class="op">$</span><span class="va">race</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">race</span>, <span class="st">"Amer-Indian-Eskimo"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Asian-Pac-Islander"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Black"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Other"</span> <span class="op">=</span> <span class="st">"Non-white"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">$</span><span class="va">race</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Non-white     White 
     4745     27816 </code></pre>
</div>
</div>
<p><strong>Lump <code>sex</code> levels</strong></p>
<p><a href="#fig-7" class="quarto-xref">Figure&nbsp;7</a> shows the number of people in each level of <code>sex</code>. Here is the code used to create it:</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">s_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sex</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>fill<span class="op">=</span><span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Sex"</span>, y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">s_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-7-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Distribution of individuals by sex.
</figcaption></figure>
</div>
</div>
</div>
<p>We see that most people in the data are male. As <code>sex</code> only has two levels, both of which are important to the analysis, we don’t do any lumping here.</p>
<p><strong>Task 8: Study the relationship between income and each of the independent variables.</strong></p>
<p>Before we build our model, we want to see if there are specific differences between people with incomes &lt;=50K and those with incomes &gt;50K. So, we examine the relationship between income and each independent variable.</p>
<p><strong>Income vs.&nbsp;Age</strong></p>
<p>We use a histogram to determine the relationship between <code>age</code> and <code>income</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">age_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"identity"</span>, alpha <span class="op">=</span> <span class="fl">0.4</span>, bins <span class="op">=</span> <span class="fl">30</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>, y <span class="op">=</span> <span class="st">"Count"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">age_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-8" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-8-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Distribution of income by age.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-8" class="quarto-xref">Figure&nbsp;8</a> shows that more people have incomes of <code>&lt;=50K</code> than of <code>&gt;50K</code>. The minimum age for people with incomes <code>&lt;=50K</code> is slightly less than that for people of the other income group. Also, the distribution of ages in the <code>&lt;=50K</code> group is heavily skewed to the right, suggesting that the mean age of this group is higher than the median age.</p>
<p><strong>Income vs.&nbsp;workclass</strong></p>
<p>Here is the code used to create the proportional stacked barplot in <a href="#fig-9" class="quarto-xref">Figure&nbsp;9</a>, showing the relationship between <code>workclass</code> and <code>income</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">wc_plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">workclass</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#f0b27a"</span>, <span class="st">"#85c1e9"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Work Class"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">wc_plot2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-9" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-9-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Distribution of income across workclass levels.
</figcaption></figure>
</div>
</div>
</div>
<p>From the barplot, we see that the <code>workclass</code> with the highest proportion of <code>&gt;50K</code> income earners is <code>Self-emp</code>, while that with the smallest proportion of this group of earners is <code>Other/Missing</code>.</p>
<p><strong>Income vs.&nbsp;Education</strong></p>
<p>Here is the code for creating the barplot in <a href="#fig-10" class="quarto-xref">Figure&nbsp;10</a>:</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ed_plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">education</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#f0b27a"</span>, <span class="st">"#85c1e9"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Education"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ed_plot2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-10" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-10-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Distribution of income across education levels.
</figcaption></figure>
</div>
</div>
</div>
<p>The barplot reveals that the <code>Prof-school</code> and <code>Doctorate</code> levels of education have the highest proportions of people with an annual income <code>&gt;50K</code>. Also, the proportion of <code>&gt;50K</code> income earners appears to increase with an increase in the level of education.</p>
<p><strong>Income vs.&nbsp;Marital Status</strong></p>
<p>We use the code below to create the barplot in <a href="#fig-11" class="quarto-xref">Figure&nbsp;11</a>:</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ms_plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">marital_status</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#f0b27a"</span>, <span class="st">"#85c1e9"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Marital Status"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ms_plot2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-11" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-11-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Distribution of income across marital_status levels.
</figcaption></figure>
</div>
</div>
</div>
<p>The barplot shows that the highest proportion of <code>&gt;50K</code> income earners are found in the <code>Married</code> group, followed by the <code>Divorced</code>, <code>Widowed</code>, <code>Separated</code>, and <code>Never-married</code> groups, in that order.</p>
<p><strong>Income vs.&nbsp;Occupation</strong></p>
<p>We create the barplot in <a href="#fig-12" class="quarto-xref">Figure&nbsp;12</a> using the following code:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">oc_plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">occupation</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#f0b27a"</span>, <span class="st">"#85c1e9"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Occupation"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">oc_plot2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-12" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-12-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Distribution of income across occupation levels.
</figcaption></figure>
</div>
</div>
</div>
<p>From the barplot, we see that the highest proportion of <code>&gt;50K</code> income earners are found in the <code>Managers</code> group, followed by the <code>Professionals</code> and <code>Technical</code> groups. The <code>Other/Missing</code> group has the lowest proportion of <code>&gt;50K</code> income earners.</p>
<p><strong>Income vs.&nbsp;Race</strong></p>
<p>The code below creates the barplot in <a href="#fig-13" class="quarto-xref">Figure&nbsp;13</a>, showing the distribution of income across race levels.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">r_plot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">race</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"fill"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#f0b27a"</span>, <span class="st">"#85c1e9"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Race"</span>, y <span class="op">=</span> <span class="st">"Proportion"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">r_plot2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-13" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-13-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Distribution of income by race.
</figcaption></figure>
</div>
</div>
</div>
<p>The barplot shows that the <code>White</code> group has a larger proportion of <code>&gt;50K</code> income earners than the <code>Non-white</code> group.</p>
<p><strong>Income vs.&nbsp;Hours/Week</strong></p>
<p>We use the code below to plot the histogram in <a href="#fig-14" class="quarto-xref">Figure&nbsp;14</a>, showing the relationship between <code>income</code> and <code>hours_per_week</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hpw_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">train_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">hours_per_week</span>, fill <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"identity"</span>, alpha <span class="op">=</span> <span class="fl">0.4</span>, bins <span class="op">=</span> <span class="fl">30</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Hours/Week"</span>, y <span class="op">=</span> <span class="st">"Count"</span>, fill <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>family <span class="op">=</span> <span class="st">"Arial"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/theme_cowplot.html">theme_cowplot</a></span><span class="op">(</span><span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">hpw_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-14" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="logistic-regression-adult-data_files/figure-html/fig-14-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Distribution of income by hours_per_week.
</figcaption></figure>
</div>
</div>
</div>
<p>From the histogram, we see that most people in the training data work about 40 hours/week. A large proportion of those who work less than 40 hours/week are <code>&lt;=50K</code> income earners. However, looking at the distribution of the <code>&gt;50K</code> income earners, the bars to the right of the 40 hours/week are longer than those to the left, meaning that many people in this income group work more than 40 hours/week.</p>
</section><section id="build-model" class="level2"><h2 class="anchored" data-anchor-id="build-model">Build Model</h2>
<p><strong>Task 9: Build a binary logistic regression model.</strong></p>
<p>We use the <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> function to build a model that predicts income group based on the variables <code>age</code>, <code>workclass</code>, <code>education</code>, <code>marital_status</code>, <code>occupation</code>, <code>race</code>, <code>sex</code>, and <code>hours_per_week</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen<span class="op">=</span><span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">model1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">income</span> <span class="op">~</span> <span class="va">.</span>, family <span class="op">=</span> <span class="st">"binomial"</span>, data <span class="op">=</span> <span class="va">train_data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = income ~ ., family = "binomial", data = train_data)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     -6.914094   0.154482 -44.757  &lt; 2e-16 ***
age                              0.028700   0.001488  19.291  &lt; 2e-16 ***
workclassOther/Missing          -1.586627   0.745594  -2.128  0.03334 *  
workclassPrivate                 0.051427   0.047502   1.083  0.27898    
workclassSelf-emp               -0.202010   0.061587  -3.280  0.00104 ** 
educationAssociate               1.706695   0.089867  18.991  &lt; 2e-16 ***
educationBachelors               2.315040   0.081844  28.286  &lt; 2e-16 ***
educationDoctorate               3.310179   0.157257  21.049  &lt; 2e-16 ***
educationHS-grad                 1.102238   0.076070  14.490  &lt; 2e-16 ***
educationMasters                 2.677012   0.097854  27.357  &lt; 2e-16 ***
educationProf-school             3.338942   0.139353  23.960  &lt; 2e-16 ***
educationSome-college            1.481604   0.079442  18.650  &lt; 2e-16 ***
marital_statusMarried            1.990770   0.060212  33.063  &lt; 2e-16 ***
marital_statusNever-married     -0.510628   0.074723  -6.834 8.28e-12 ***
marital_statusSeparated         -0.143951   0.145438  -0.990  0.32228    
marital_statusWidowed           -0.018087   0.134534  -0.134  0.89305    
occupationOther/Missing          0.874156   0.746557   1.171  0.24163    
occupationLabor-trades          -0.323266   0.067238  -4.808 1.53e-06 ***
occupationManagers               0.740283   0.069897  10.591  &lt; 2e-16 ***
occupationService-sales-workers -0.054056   0.067894  -0.796  0.42593    
occupationProfessionals          0.404060   0.073506   5.497 3.86e-08 ***
occupationTechnical              0.539975   0.103518   5.216 1.83e-07 ***
raceWhite                        0.280506   0.053006   5.292 1.21e-07 ***
sexMale                          0.313347   0.046955   6.673 2.50e-11 ***
hours_per_week                   0.030166   0.001460  20.655  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 35948  on 32560  degrees of freedom
Residual deviance: 23743  on 32536  degrees of freedom
AIC: 23793

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>The model we’ve built above can be written algebraically as</p>
<p><span class="math display">\[\ln(\frac{\rho}{1-\rho}) = \beta_{0} + \beta_{1}X_{1} + \cdots + \beta_{p}X_{p}, \]</span></p>
<p>where <span class="math inline">\(X_1, \cdots, X_p\)</span> are the predictor variables, <span class="math inline">\(β_0, \cdots ,β_p\)</span> are the regression coefficients, <span class="math inline">\(\rho\)</span> is the probability of success, i.e., the probability of obtaining a particular value of the target variable, and <span class="math inline">\(\frac{\rho}{1-\rho}\)</span> is the odds for success.</p>
<p>The target, income, is a factor with two levels <code>&lt;=50K</code> and <code>&gt;50K</code>. R interprets the first level, <code>&lt;=50K</code>, as failure and the second level, <code>&gt;50K</code>, as success. For more information on how the <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> function handles the levels of factor variables, use the command <code><a href="https://rdrr.io/r/stats/glm.html">?glm</a></code> to access the function’s documentation pages.</p>
<p>For a continuous predictor, the regression coefficient gives the change in the log odds for success when the predictor increases by 1 unit. We can also say that the regression coefficient is the log of the odds ratio comparing people who differ in that predictor by 1 unit, when the remaining predictors are held fixed <span class="citation" data-cites="uclalogit">(<a href="#ref-uclalogit" role="doc-biblioref">UCLA: Statistical Consulting Group, n.d.</a>)</span>. For example, from the regression output above,</p>
<ul>
<li><p>A 1 unit increase in <code>age</code> should result in a 0.029 increase in the log odds of income being <code>&gt;50K</code>.</p></li>
<li><p>A 1 unit increase in <code>hours_per_week</code> should result in a 0.030 increase in the log odds of income being <code>&gt;50K</code>.</p></li>
</ul>
<p>By contrast, the regression coefficient for a level of a categorical predictor gives the log of the odds ratio comparing people at the given level to those at the base level, when other predictors are held fixed. So, it is crucial for the base level to be a meaningful quantity.</p>
<p>From the regression output above, we can say that</p>
<ul>
<li><p>The log of the odds ratio for income being <code>&gt;50K</code> comparing <code>males</code> to <code>females</code> is 0.313.</p></li>
<li><p>The log of the odds ratio for income being <code>&gt;50K</code> comparing <code>whites</code> to <code>non-whites</code> is 0.281.</p></li>
<li><p>The log of the odds ratio for income being <code>&gt;50K</code> comparing each level of education to the base level, <code>Pre-school-12th</code>, is greater than 1</p></li>
</ul>
<p>We can also exponentiate the regression coefficients to give odd ratios. Here is the code:</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">model1</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    (Intercept)                             age 
                   9.936811e-04                    1.029116e+00 
         workclassOther/Missing                workclassPrivate 
                   2.046146e-01                    1.052772e+00 
              workclassSelf-emp              educationAssociate 
                   8.170866e-01                    5.510721e+00 
             educationBachelors              educationDoctorate 
                   1.012533e+01                    2.739002e+01 
               educationHS-grad                educationMasters 
                   3.010897e+00                    1.454158e+01 
           educationProf-school           educationSome-college 
                   2.818928e+01                    4.399996e+00 
          marital_statusMarried     marital_statusNever-married 
                   7.321172e+00                    6.001186e-01 
        marital_statusSeparated           marital_statusWidowed 
                   8.659304e-01                    9.820751e-01 
        occupationOther/Missing          occupationLabor-trades 
                   2.396851e+00                    7.237814e-01 
             occupationManagers occupationService-sales-workers 
                   2.096528e+00                    9.473788e-01 
        occupationProfessionals             occupationTechnical 
                   1.497894e+00                    1.715964e+00 
                      raceWhite                         sexMale 
                   1.323799e+00                    1.367996e+00 
                 hours_per_week 
                   1.030626e+00 </code></pre>
</div>
</div>
<p>From the output above, we can now say that</p>
<ul>
<li><p>The odds of income being <code>&gt;50K</code> increases by 1.029 when <code>age</code> increases by 1 unit.</p></li>
<li><p>The odds of income being <code>&gt;50K</code> increases by 1.031 when <code>hours_per_week</code> increases by 1 unit.</p></li>
<li><p>The odds ratio for income being <code>&gt;50K</code> comparing males to females is 1.368.</p></li>
<li><p>The odds ratio for income being <code>&gt;50K</code> comparing whites to non-whites is 1.324.</p></li>
<li><p>The odds ratio for income being <code>&gt;50K</code> comparing each level of education to the base level, <code>Pre-school-12th</code>, is greater than 1.</p></li>
</ul></section><section id="model-evaluation" class="level2"><h2 class="anchored" data-anchor-id="model-evaluation">Model Evaluation</h2>
<p><strong>Task 10: Determine baseline accuracy</strong></p>
<p>We set the baseline accuracy as the proportion of the majority class because a naïve model is highly likely to always predict this class.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">[</span><span class="va">train_data</span><span class="op">$</span><span class="va">income</span> <span class="op">==</span> <span class="st">'&lt;=50K'</span>, <span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">train_data</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.76</code></pre>
</div>
</div>
<p>So, the baseline accuracy score is 0.76. Because the dataset is slightly imbalanced, with approximately 76% of the data belonging to the “&lt;=50K” class, it’s better to use the balanced accuracy score to evaluate the performance of the logistic regression model. We explain how to calculate this and other evaluation metrics in <strong>Task 11</strong>.</p>
<p><strong>Task 11: Determine the training and test accuracies for the model.</strong></p>
<p>We can use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function to get the probability of an individual earning a <code>&gt;50K</code> income. If this probability is greater than 0.5, we assume that the individual earns a <code>&gt;50K</code> income. Otherwise, they earn a <code>&lt;=50K</code> income. We use the <code><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix()</a></code> function from the <code>caret</code> package to compare the predicted income with the actual income.</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model1</span>, newdata <span class="op">=</span> <span class="va">train_data</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">pred_income</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">prob</span> <span class="op">&gt;</span> <span class="fl">0.5</span>, <span class="st">"&gt;50K"</span>, <span class="st">"&lt;=50K"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix</a></span><span class="op">(</span><span class="va">pred_income</span>, <span class="va">train_data</span><span class="op">$</span><span class="va">income</span>, positive <span class="op">=</span> <span class="st">"&gt;50K"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction &lt;=50K  &gt;50K
     &lt;=50K 22861  3753
     &gt;50K   1859  4088
                                          
               Accuracy : 0.8276          
                 95% CI : (0.8235, 0.8317)
    No Information Rate : 0.7592          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.4863          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.5214          
            Specificity : 0.9248          
         Pos Pred Value : 0.6874          
         Neg Pred Value : 0.8590          
             Prevalence : 0.2408          
         Detection Rate : 0.1255          
   Detection Prevalence : 0.1826          
      Balanced Accuracy : 0.7231          
                                          
       'Positive' Class : &gt;50K            
                                          </code></pre>
</div>
</div>
<p>From the output above, we see that the train accuracy (0.8276) is better than the previously computed baseline accuracy, called the No Information Rate (0.7592) in the output.</p>
<p>Other important statistics generated by <code><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix()</a></code> are defined below <span class="citation" data-cites="Lee2025">(<a href="#ref-Lee2025" role="doc-biblioref">Lee 2023</a>)</span>:</p>
<ul>
<li><p>True positives (TP): the number of events the model correctly classifies as positive. In this case, TP = 4088.</p></li>
<li><p>True negatives (TN): the number of events the model correctly classifies as negative. In this case, TN = 22861.</p></li>
<li><p>False positives (FP): the number of events the model incorrectly classifies as positive. In this case, FP = 1859.</p></li>
<li><p>False negatives (FN): the number of events the model incorrectly classifies as negative. In this case, FN = 3753.</p></li>
<li><p>P-Value [Acc &gt; NIR]: the p value of a statistical test indicating whether the model’s accuracy is significantly better than the NIR.</p></li>
<li><p>Kappa (also called Cohen’s kappa): a measure of how well the model’s predictions agree with actual values. It ranges from -1 to 1. A less than 0 value suggests an agreement worse than chance, and a greater than 0 value suggests an agreement better than chance.</p></li>
<li><p>Mcnemar’s Test P-Value: the p value of a statistical test comparing the number of false positives to false negatives. A large p value suggests no significant difference between the two groups.</p></li>
<li><p>Sensitivity (also called recall or true positive rate): the proportion of actual positive events correctly classified by the model. It is calculated as <span class="math inline">\(\frac{TP}{TP + FN}\)</span>.</p></li>
<li><p>Specificity (also called true negative rate): the proportion of actual negative events correctly classified by the model. It is calculated as <span class="math inline">\(\frac{TN}{FP + TN}\)</span></p></li>
<li><p>Positive predictive value (also called precision): the proportion of positive predictions that were true. It is calculated as <span class="math inline">\(\frac{TP}{TP + FP}\)</span>.</p></li>
<li><p>Negative Predictive Value: the proportion of negative predictions that were true. It is calculated as <span class="math inline">\(\frac{TN}{TN + FN}\)</span>.</p></li>
<li><p>Prevalence: the proportion of actually positive events in the dataset. It is the same as the “No Information Rate” also given in this output and calculated as <span class="math inline">\(\frac{TP + FN}{TP + FP + TN + FN}\)</span></p></li>
<li><p>Detection Rate: the proportion of true positives in the dataset. It is calculated as <span class="math inline">\(\frac{TP}{TP + FP + TN + FN}\)</span>.</p></li>
<li><p>Detection Prevalence: the proportion of events predicted as positive. It is calculated as <span class="math inline">\(\frac{TP + FP}{TP + FP + TN + FN}\)</span>.</p></li>
<li><p>Balanced Accuracy: the average of specificity and sensitivity.</p></li>
</ul>
<p>As we’ve already mentioned, instead of using the standard accuracy score to evaluate the model’s performance, we can use the balanced accuracy, which is a more reliable measure of performance when dealing with imbalanced datasets. The balanced accuracy score for the baseline model is 0.5, while that for the logistic regression model is 0.7231. This result suggests that the model has learned meaningful patterns from the data and is not merely guessing the majority class.</p>
<p>Next, we look at the model’s performance on the test data. But we must first import the data and transform it the same way we transformed the training data.</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Read test data.</span></span>
<span><span class="co"># We skip the first line of the dataset (skip = 1) because it doesn’t</span></span>
<span><span class="co"># contain useful information.</span></span>
<span><span class="va">test_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"C:/Users/User/Desktop/Logistic_Regression_ADULT/Data/adult.test"</span>, skip <span class="op">=</span> <span class="fl">1</span>, header <span class="op">=</span> <span class="cn">FALSE</span>, sep <span class="op">=</span> <span class="st">","</span>, strip.white <span class="op">=</span> <span class="cn">TRUE</span>, stringsAsFactors <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co"># Name columns</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"workclass"</span>, <span class="st">"fnlwgt"</span>, <span class="st">"education"</span>, <span class="st">"education_num"</span>, <span class="st">"marital_status"</span>, <span class="st">"occupation"</span>, <span class="st">"relationship"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>, <span class="st">"capital_gain"</span>, <span class="st">"capital_loss"</span>, <span class="st">"hours_per_week"</span>, <span class="st">"native_country"</span>, <span class="st">"income"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Get an overview of the test data:</p>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   16281 obs. of  15 variables:
 $ age           : int  25 38 28 44 18 34 29 63 24 55 ...
 $ workclass     : Factor w/ 9 levels "?","Federal-gov",..: 5 5 3 5 1 5 1 7 5 5 ...
 $ fnlwgt        : int  226802 89814 336951 160323 103497 198693 227026 104626 369667 104996 ...
 $ education     : Factor w/ 16 levels "10th","11th",..: 2 12 8 16 16 1 12 15 16 6 ...
 $ education_num : int  7 9 12 10 10 6 9 15 10 4 ...
 $ marital_status: Factor w/ 7 levels "Divorced","Married-AF-spouse",..: 5 3 3 3 5 5 5 3 5 3 ...
 $ occupation    : Factor w/ 15 levels "?","Adm-clerical",..: 8 6 12 8 1 9 1 11 9 4 ...
 $ relationship  : Factor w/ 6 levels "Husband","Not-in-family",..: 4 1 1 1 4 2 5 1 5 1 ...
 $ race          : Factor w/ 5 levels "Amer-Indian-Eskimo",..: 3 5 5 3 5 5 3 5 5 5 ...
 $ sex           : Factor w/ 2 levels "Female","Male": 2 2 2 2 1 2 2 2 1 2 ...
 $ capital_gain  : int  0 0 0 7688 0 0 0 3103 0 0 ...
 $ capital_loss  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ hours_per_week: int  40 50 40 40 30 30 40 32 40 10 ...
 $ native_country: Factor w/ 41 levels "?","Cambodia",..: 39 39 39 39 39 39 39 39 39 39 ...
 $ income        : Factor w/ 2 levels "&lt;=50K.","&gt;50K.": 1 1 2 2 1 1 1 2 1 1 ...</code></pre>
</div>
</div>
<p>The dataset has 16281 observations and 15 variables. When we compare feature levels between the training and the test datasets, we see a match. Only the variables <code>workclass</code>, <code>occupation</code>, and <code>native_country</code> have missing values in both datasets, so we can use the same methods used to clean the training set to clean the test data. In addition, we should remove the dots in the test dataset’s income levels so they match the training dataset’s income levels.</p>
<p>First, we get rid of all the variables we don’t need, i.e., <code>capital_gain</code>, <code>capital_loss</code>, <code>native_country</code>, <code>education_num</code>, <code>fnlwgt</code>, and <code>relationship</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">capital_gain</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">capital_loss</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">native_country</span> <span class="op">&lt;-</span> <span class="cn">NULL</span> </span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">education_num</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">fnlwgt</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">test_data</span><span class="op">$</span><span class="va">relationship</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we use the <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code> function from the <code>dplyr</code> package to recode missing values and lump predictor levels.</p>
<p><strong>Lump <code>workclass</code> levels</strong></p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">workclass</span>, <span class="st">"?"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"Federal-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Local-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Never-worked"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"Self-emp-inc"</span> <span class="op">=</span> <span class="st">"Self-emp"</span>, <span class="st">"Self-emp-not-inc"</span> <span class="op">=</span> <span class="st">"Self-emp"</span>, <span class="st">"State-gov"</span> <span class="op">=</span> <span class="st">"Gov"</span>, <span class="st">"Without-pay"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we make “Gov” the base level of the variable.</p>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">workclass</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">workclass</span>, ref <span class="op">=</span> <span class="st">"Gov"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>education</code> levels</strong></p>
<div class="cell">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">education</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">education</span>, <span class="st">"10th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"11th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"12th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"1st-4th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"5th-6th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"7th-8th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"9th"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span>, <span class="st">"Assoc-acdm"</span> <span class="op">=</span> <span class="st">"Associate"</span>, <span class="st">"Assoc-voc"</span> <span class="op">=</span> <span class="st">"Associate"</span>, <span class="st">"Preschool"</span> <span class="op">=</span> <span class="st">"Preschool-12th"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>marital_status</code> levels</strong></p>
<div class="cell">
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">marital_status</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">marital_status</span>, <span class="st">"Married-AF-spouse"</span> <span class="op">=</span> <span class="st">"Married"</span>, <span class="st">"Married-civ-spouse"</span> <span class="op">=</span> <span class="st">"Married"</span>, <span class="st">"Married-spouse-absent"</span> <span class="op">=</span> <span class="st">"Married"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>occupation</code> levels</strong></p>
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">occupation</span>, <span class="st">"Protective-serv"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Sales"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Priv-house-serv"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Other-service"</span> <span class="op">=</span> <span class="st">"Service-sales-workers"</span>, <span class="st">"Exec-managerial"</span> <span class="op">=</span> <span class="st">"Managers"</span>, <span class="st">"Prof-specialty"</span> <span class="op">=</span> <span class="st">"Professionals"</span>, <span class="st">"Tech-support"</span> <span class="op">=</span> <span class="st">"Technical"</span>, <span class="st">"Adm-clerical"</span> <span class="op">=</span> <span class="st">"Clerical"</span>, <span class="st">"Machine-op-inspct"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Handlers-cleaners"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Farming-fishing"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Craft-repair"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Transport-moving"</span> <span class="op">=</span> <span class="st">"Labor-trades"</span>, <span class="st">"Armed-Forces"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span>, <span class="st">"?"</span> <span class="op">=</span> <span class="st">"Other/Missing"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we reorder occupation levels to make <code>Clerical</code> the base level.</p>
<div class="cell">
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">occupation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">occupation</span>, ref <span class="op">=</span> <span class="st">"Clerical"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Lump <code>race</code> levels</strong></p>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">race</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">race</span>, <span class="st">"Amer-Indian-Eskimo"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Asian-Pac-Islander"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Black"</span> <span class="op">=</span> <span class="st">"Non-white"</span>, <span class="st">"Other"</span> <span class="op">=</span> <span class="st">"Non-white"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Clean <code>income</code> levels</strong></p>
<p>We remove the dots in <code>income</code> level names, as shown below.</p>
<div class="cell">
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_data</span><span class="op">$</span><span class="va">income</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">test_data</span><span class="op">$</span><span class="va">income</span>, <span class="st">"&lt;=50K."</span> <span class="op">=</span> <span class="st">"&lt;=50K"</span>, <span class="st">"&gt;50K."</span> <span class="op">=</span> <span class="st">"&gt;50K"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having cleaned the test dataset, we can now use the <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> function to make predictions on the test set. We then use <code><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix()</a></code> to compute the test accuracy score and other metrics.</p>
<div class="cell">
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model1</span>, newdata <span class="op">=</span> <span class="va">test_data</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">pred_income_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">prob_test</span> <span class="op">&gt;</span> <span class="fl">0.5</span>, <span class="st">"&gt;50K"</span>, <span class="st">"&lt;=50K"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/caret/man/confusionMatrix.html">confusionMatrix</a></span><span class="op">(</span><span class="va">pred_income_test</span>, <span class="va">test_data</span><span class="op">$</span><span class="va">income</span>, positive <span class="op">=</span> <span class="st">"&gt;50K"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction &lt;=50K  &gt;50K
     &lt;=50K 11498  1827
     &gt;50K    937  2019
                                         
               Accuracy : 0.8302         
                 95% CI : (0.8244, 0.836)
    No Information Rate : 0.7638         
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
                                         
                  Kappa : 0.4887         
                                         
 Mcnemar's Test P-Value : &lt; 2.2e-16      
                                         
            Sensitivity : 0.5250         
            Specificity : 0.9246         
         Pos Pred Value : 0.6830         
         Neg Pred Value : 0.8629         
             Prevalence : 0.2362         
         Detection Rate : 0.1240         
   Detection Prevalence : 0.1816         
      Balanced Accuracy : 0.7248         
                                         
       'Positive' Class : &gt;50K           
                                         </code></pre>
</div>
</div>
<p>From the output above, we see that the test accuracy is 0.83, which is slightly better than the train accuracy. Also, the test balanced accuracy (0.7248) is slightly higher than the training balanced accuracy (0.7231). So, we can conclude that the model probably generalizes well on new data.</p>
</section><section id="references" class="level2">



</section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-adult_2" class="csl-entry" role="listitem">
Becker, Barry, and Ronny Kohavi. 1996. <span>“<span>Adult</span>.”</span> UCI Machine Learning Repository.
</div>
<div id="ref-boehmke2019" class="csl-entry" role="listitem">
Boehmke, Brad, and Brandon M. Greenwell. 2019. <em>Hands-on Machine Learning with <span>R</span></em>. New York: CRC Press.
</div>
<div id="ref-Lee2025" class="csl-entry" role="listitem">
Lee, Changjun. 2023. <span>“Understanding the Confusion Matrix and ROC Curve in <span>R</span>.”</span> <a href="https://changjunlee.com/blogs/posts/4_confusion_mat_and_roc" class="uri">https://changjunlee.com/blogs/posts/4_confusion_mat_and_roc</a>.
</div>
<div id="ref-uclalogit" class="csl-entry" role="listitem">
UCLA: Statistical Consulting Group. n.d. <span>“Logit Regression | <span>R</span> Data Analysis Examples.”</span> <a href="https://stats.oarc.ucla.edu/r/dae/logit-regression/">https://stats.oarc.ucla.edu/r/dae/logit-regression/</a>.
</div>
</div></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Ruth Ogal.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.</p>
</div>
  </div>
</footer>


</body></html>